#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#
# (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#     not find so, but you have some other POSIX shell (ksh, bash, zsh, sh), you
#     may specify it explicitly by setting the SHELL variable when running this
#     script. Example:
#
#       SHELL=/bin/ksh ./gradlew <args>
#
# (2) Busybox and similar reduced shells will NOT work, because this script
#     requires all of these POSIX shell features:
#       * functions;
#       * expansions "$var", "${var}", "${var:-default}", "${var+SET}",
#       * compound commands having a testable exit status, especially "case";
#       * various built-in commands including "command", "set", and "ulimit".
#
# Important for patching:
#
# (1) This script targets any POSIX shell, so avoiding extensions provided
#     by Bash, Ksh, etc; in particular arrays.
#
# (2) When this script is executed directly, it may be the last line of the
#     script to execute (thus "exec"), which means that "local" extensions
#     may not be sourced. That is why the "." operator is used with
#     "source" instead.
# See the License for the specific language governing permissions and
# limitations under the License.
#
##############################################################################

if [ "$(uname)" = "Darwin" ] ; then
    APP_NAME="Gradle"
    APP_REAL_NAME=$(basename "$0")
else
    APP_NAME="Gradle"
    APP_REAL_NAME=$(basename "$0")
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='" \"-Xmx64m\" \"-Xms64m\""'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn ( ) {
    echo "$*" >&2
}

die ( ) {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
native=false
case "$( uname )" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NATIVEIMAGE )
    native=true
    ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$darwin" = "false" ] && [ "$native" = "false" ] ; then
    MAX_FD_LIMIT=$( ulimit -H -n )
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if [ "$darwin" = "true" ] ; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_BASE_DIR/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    JAVACMD=$( cygpath --windows "$JAVACMD" )
    for i do
        arg=$( cygpath --windows "$i" )
        # TODO(cseitz): once we switch to Java 9, we can use the array command.
        #            quoted=( "${quoted[@]}" "$arg" )
        #            Doing it this way because bash on Windows doesn't behave the same
        eval "args$i=\"$arg\""
    done
    i=$((count+1))
fi

if [ -n "$JAVA_TOOL_OPTIONS" ] ; then
    JAVA_OPTS="$JAVA_OPTS $JAVA_TOOL_OPTIONS"
fi

if [ -n "$GRADLE_OPTS" ] ; then
    GRADLE_OPTS=$( echo $GRADLE_OPTS | xargs )
fi

exec "$JAVACMD" \
  $JAVA_OPTS \
  $GRADLE_OPTS \
  -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
